[build]
  base = "blogs-app"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/blogs/*"
  to = "/blogs/:splat"
  status = 200
